### ISSUE TITLE
Font when using ui theme light

### ISSUE THREAD

**Issue by rudibroekhuizen** [boazreicher/mosaic-plot#3]
When the Grafana UI theme is set to light, the font next to the x and y axis look weird. When using the dark theme it looks fine.

![Screenshot from 2022-07-07 12-07-44](https://user-images.githubusercontent.com/4686274/177762209-401ca024-e0e3-43f0-8f61-98276e9676a3.png)

**Comment by boazreicher** [comment]
Fixed in release [v1.0.14](https://github.com/boazreicher/mosaic-plot/releases/tag/v1.0.14)

I submitted the fixed version for review, it will probably be available in [Grafana Plugins](https://grafana.com/grafana/plugins/) within a few days.

If you want, you can also manually download and install from [here](https://github.com/boazreicher/mosaic-plot/releases/download/v1.0.14/boazreicher-mosaicplot-panel-1.0.14.zip)

**Comment by rudibroekhuizen** [comment]
Great, thanks.

**Comment by boazreicher** [comment]
The fixed version has been updated in Grafana

**Comment by boazreicher** [comment]
@rudibroekhuizen can you please let me know if this issue can be closed?

**Comment by rudibroekhuizen** [comment]
Yes, this issue can be closed, thanks!
